name: Deploy to Maven Central and GitHub Releases

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 with Token Authentication
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: OSSRH_USER
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract version from tag
        id: extract_version
        run: |
          run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set POM version
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false
          mvn versions:commit

      - name: Build and Deploy to Maven Central
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn clean deploy -DskipTests=true

      - name: Upload JARs and Signatures to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/ser-mail-api-${{ env.VERSION }}.jar
            ./target/ser-mail-api-${{ env.VERSION }}.jar.asc
            ./target/ser-mail-api-${{ env.VERSION }}-sources.jar
            ./target/ser-mail-api-${{ env.VERSION }}-sources.jar.asc
            ./target/ser-mail-api-${{ env.VERSION }}-javadoc.jar
            ./target/ser-mail-api-${{ env.VERSION }}-javadoc.jar.asc
