name: Publish to Maven Central

on:
  release:
    types: [published] # Trigger when a release is published (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for Git tagging

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_KEY }}" | gpg --import
          echo "GPG key imported successfully"

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}  # Remove 'v' prefix
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B release:prepare release:perform \
            -Drelease.version=${{ steps.extract_version.outputs.version }} \
            -DdevelopmentVersion=${{ steps.extract_version.outputs.version }}-SNAPSHOT \
            -Dtag=${{ github.event.release.tag_name }} \
            -Darguments="-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"

      - name: Verify deployment
        run: echo "Published version ${{ github.event.release.tag_name }} to Maven Central"